### ISSUE TITLE
2.4 - As a student I want to create my own profile so that I can let other students see me

### ISSUE THREAD

**Issue by leongkkevin** [Cry1is/Team1_Project#17]
Size - 1

Given a user is not fullfied the profile, when they want to add something frm their profile, the user should be allow to add things.

Given a user is fullfied the profile, when they want to delete or change something from their profile, the user should be allow to delete and change things.

**Comment by wesoa012** [comment]
Done, Merging tomorrow.

**Comment by wesoa012** [comment]
Profile page is done. Users are able to edit there profile. Working on Profile pictures, however everything else is done
