### ISSUE TITLE
3.4 - As a student I want to choose the same class as my friends so that I can study with friends together

### ISSUE THREAD

**Issue by alexanderr** [Cry1is/Team1_Project#19]
Given a user who is eligible for a class, when they click on a class their friend is enrolled in, redirect to the enrollment page for that class.

Given a user who is not eligible for a class, when they click on the class their friend is enrolled in, inform the user that they are ineligible for that class.

Size: 5

**Comment by wesoa012** [comment]
Friends part is up, working on class information. Should be done within the week

**Comment by wesoa012** [comment]
Users able to view friends classes
