### ISSUE TITLE
3.6 - As a student I want to be able to see what classes my friends so that I can share notes and ask them for help with assignments

### ISSUE THREAD

**Issue by alexanderr** [Cry1is/Team1_Project#28]
Given a user who is friends with A, when they click on A's profile, display the classes they have been enrolled in.

Given a user who is not friends with A, when they click on A's profile, do not display the classes they have been enrolled in.

Size: 1

**Comment by wesoa012** [comment]
90% there, friends part is online, waiting for classes information to be available

**Comment by wesoa012** [comment]
Same issue as other one

**Comment by wesoa012** [comment]
Again, don't know if this was the branch, but this issue is implemented
