### ISSUE TITLE
3.5 - As a student I want my friends to be able to see which courses I'm taking so that I can be in classes with people I know

### ISSUE THREAD

**Issue by alexanderr** [Cry1is/Team1_Project#33]
Given a user who is friends with A, when they click on A's profile, display the classes they are enrolled in

Given a user who is not friends with A, when they click on A's profile, do not display the classes they are enrolled in

Size: 2

**Comment by wesoa012** [comment]
90% there, friends is online, working on classes display

**Comment by wesoa012** [comment]
This is implemented

**Comment by wesoa012** [comment]
I think it was this but i got no clue

**Comment by wesoa012** [comment]
I mean the thing is definitely implemented
