### ISSUE TITLE
7.5 - As a Professor/TA I want to notify admin easily if I have had multiple reports of students wanting more seats in my class so that I can provide more students the opportunity to join my course

### ISSUE THREAD

**Issue by leongkkevin** [Cry1is/Team1_Project#42]
Size - 34

Given that a user has teacher admin privileges, if they want to add more seats to their classes, there should be a "Request" button where they can submit a request form stating the number of seats they wish to be added, the reason why they want more seats, and their plan for adapting to the new number of students

Given that a teacher has already submitted a request form, they can go into their personal profile and view the form they submitted, as well as the reply from admin if they have received one.

Given that a teacher has reached out to admin but has not heard back in a few days, they can press a "remind" button within their profile page with the list of submitted forms to bump their request back to the top of the admin's inbox.

**Comment by RebeccaEKuhlman** [comment]
Notification implemented, no automatic notifications
