### ISSUE TITLE
7.6 - As a university staff/admin I want to receive timely reports of teachers that want seats added so that I can accommodate their requests quickly and efficiently

### ISSUE THREAD

**Issue by leongkkevin** [Cry1is/Team1_Project#46]
Size - 34

Given that a teacher submitted a request to add more seats, the admin will be notified of this request immediately and be able to review the teacher's reason for this request as well as the teacher's plan to accommodate more students.

Given that a teacher pushes the "Remind" button on a request not yet addressed, the admin will see this request moved to the top of their inbox

**Comment by RebeccaEKuhlman** [comment]
Notification created, auto notifications not
